### ISSUE TITLE
Deprecated Fixnum warnings

### ISSUE THREAD

**Issue by TheotimeBollengier** [aarongough/sexpistol#2]
Since Ruby 2.4, Fixnum and Bignum have been unified into Integer, So whenever we use sexpistol, we get the Fixnum deprecation warning.

Would it be possible to change line 25 of file sexpistol_parser.rb
"when String, Fixnum, Float, Symbol"
to replace Fixnum by Integer,
or, to keep compatibility with previous Ruby versions,
use 1.class instead of Fixnum

It would be nice not to have this warning anymore.

Regards,
Théotime

**Comment by aarongough** [comment]
Hello Théotime!
Sorry for taking 4 years to respond to your note! I have not had much time to work on open source stuff the last few years!

I have made a large update to this project including many fixes, one of which is fixing the `Fixnum` warnings. The new gem version will be `0.10.0` and will be released shortly. It requires Ruby `> 2.5.0`.

Thanks for reporting this issue!
-Aaron
